# RocketMQ Broker 配置文件

# 集群名称
brokerClusterName=DefaultCluster

# Broker 名称
brokerName=broker-a

# Broker ID
brokerId=0

# 删除文件时间点，默认凌晨4点
deleteWhen=04

# 文件保留时间，默认48小时
fileReservedTime=48

# Broker 角色
brokerRole=ASYNC_MASTER

# 刷盘方式
flushDiskType=ASYNC_FLUSH

# Name Server 地址
namesrvAddr=rmqnamesrv:9876

# 监听端口
listenPort=10911

# 存储路径
storePathRootDir=/home/rocketmq/store
storePathCommitLog=/home/rocketmq/store/commitlog

# 消费队列路径
storePathConsumeQueue=/home/rocketmq/store/consumequeue
storePathIndex=/home/rocketmq/store/index
storeCheckpoint=/home/rocketmq/store/checkpoint
abortFile=/home/rocketmq/store/abort

# 限制消息大小
maxMessageSize=65536

# 刷盘间隔
flushIntervalCommitLog=500

# 刷盘间隔
flushIntervalConsumeQueue=1000

# Broker IP
brokerIP1=rmqbroker

# 自动创建主题
autoCreateTopicEnable=true

# 自动创建订阅组
autoCreateSubscriptionGroup=true
